MeuSite/urls.py
from django.contrib import admin
from django.urls import path, include

#Fui alertado a não fazer isto em produção realmente, apenas aqui para fins de testes!!!
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
from django.conf import settings
from django.conf.urls.static import static
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #Isso não deveria ser feito em ambiente de produção, apenas em desenvolvimento para fins de treinamento, em pcp. Apesar que não consegui fazer aparecer a imagem...

core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contato'),
    path('cadastro/', views.cadastro, name='cadastro'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Categoria(models.Model):
    nome = models.CharField(max_length=255)

    class Meta:
        ordering = ('nome',) #Aqui ordenamos as categorias em ordem alfabética.
        verbose_name_plural = 'Categorias' #Aqui eu altero a forma como o Django vai transformar em plural as palavras que eu escrever.

    def __str__(self):
        return self.nome #Aqui é para aparecerem os nomes das categorias, ao invés de 'categoria object'
    
    #Após criarmos as categorias, vamos criar os itens que irão se enquadrar em alguma categoria.

class Item(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='items', on_delete=models.CASCADE) #Esse Cascade, como visto na matéria Banco de Dados, quer dizer que se o conjunto Categoria for deletado, todos os itens atrelados a ele também serão deletados, por efeito cascata.
    nome = models.CharField(max_length=255)
    descricao = models.TextField(blank=True, null=True)
    preco = models.FloatField()
    imagem = models.ImageField(upload_to='item_images', blank=True, null=True)
    vendido = models.BooleanField(default=False)
    vendedor = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    data_criacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('nome',) #Aqui ordenamos as categorias em ordem alfabética.
        verbose_name_plural = 'Itens'

    def __str__(self):
        return self.nome

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Cadastro(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2') #Senha 1 e senha 2 são apenas para o usuário repetir e vermos se ele escrever a senha igual, na hora de se cadastrar.

        #Aqui vamos deixar um pouco mais arrumadinho cada um dos campos:
        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Seu nome de usuário',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
        email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'Seu endereço de e-mail',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
        password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Senha',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
        password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'Repita sua senha',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
        #Percebam, in loco, que não mudou nada no site...

core/views.py
from django.shortcuts import render, redirect

from item.models import Categoria, Item

from .forms import Cadastro
# Create your views here.
#Aqui no arquivo views vamos criar todas as páginas que forem existir no meu site.

#Iniciamos criando uma página chamada index, que será nossa front page.
def index(request):
    itens = Item.objects.filter(vendido=False)[0:6]
    categorias = Categoria.objects.all()
    return render(request, 'core/index.html', {
        'categorias': categorias,
        'itens': itens,
    })

#Na sequência vamos criando as páginas a seguir:
def contact(request):
    return render(request, 'core/contact.html')

def cadastro(request):
    if request.method == 'POST':
        form = Cadastro(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else: 
        form = Cadastro()
    return render(request, 'core/cadastro.html', {
        'form': form
    })

item/views.py
from django.shortcuts import render, get_object_or_404

from .models import Item

# Create your views here.
#Criando as visualizações detalhadas de cada item:
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(categoria=item.categoria, vendido=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-widht, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title> {% block title %} {% endblock %} | Meu Site </title>

    </head>

    <body>

        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-bold">Meu Site</a>

            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Um link aqui</a>
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Outro link</a>

                <a href="{% url 'core:cadastro'%}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Novo Usuário</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Sobre</h3>
                <p class="text-lg text-gray-500">Esse foi um site desenvolvido em Python, utilizando o Framework Django, para fins de teste e aprendizado sobre a utilização do referido Framework, pra eu conseguir ajudar a sustentar minha esposa e filhos queridos!</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Sobre</a></li>
                    <li><a href="{% url 'core:contato' %}" class="text-lg text-teal-500 hover:text-teal-700">Contato</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Politica de Privacidade</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Termos de Uso</a></li>
                </ul>
            </div>

        </footer>

    </body>

</html>

core/templates/core/cadastro.html
{% extends 'core/base.html'%}

{% block title %} Cadastro {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Cadastro de Usuário</h1>
    
    <form method="post" action=".">
        {% csrf_token %}

        <div>
            <label class="inline-block mb-2">Usuário: </label><br>
            {{ form.username }}
        </div>

        <div>
            <label class="inline-block mb-2">E-mail: </label><br>
            {{ form.email }}
        </div>

        <div>
            <label class="inline-block mb-2">Senha: </label><br>
            {{ form.password1 }}
        </div>

        <div>
            <label class="inline-block mb-2">Repita a senha: </label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{field.errors}}
                {% endfor %}

                {{ form.non_field_errors}}

            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Cadastrar</button>

    </form>
</div>
{% endblock %}

core/templates/core/contact.html
{% extends 'core/base.html'%}

{% block title %} Contatos {% endblock %}

{% block content %}
    <h1>Página de Contatos</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html'%}

{% block title %} Bem-Vindos {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Novos Itens!</h2>
    </div>

    <div class="grid grid-cols-3 gap-3">
        {% for item in itens %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.imagem.url }}" class="rounded-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.nome }}</h2>
                        <p class="text-gray-500">Preço: {{ item.preco }} </p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categorias</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for categoria in categorias %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ categoria.nome }}</h2>
                            <p class="text-gray-500">{{ categoria.items.count }} itens</p> 
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    
    </div>
{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %} {{item.nome}} {% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.imagem.url }}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.nome}}</h1>
        <p class="text-gray-500"><strong>Preço: </strong>{{item.preco}}</p>
        <p class="text-gray-500"><strong>Vendedor: </strong>{{item.vendedor.username}}</p>

        {% if item.descricao %}
            <p class="text-gray-700">
                <strong class="text-gray-500"> Descrição: </strong><br>
                {{item.descricao}}
            </p>
        {% endif %}

        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contatar Vendedor</a>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Itens Relacionados</h2>
</div>

<div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.imagem.url }}" class="rounded-xl">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ item.nome }}</h2>
                    <p class="text-gray-500">Preço: {{ item.preco }} </p>
                </div>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}